key: configurationScore
name: Defender Configuration Score
table: DefenderConfigurationScore_CL
schedule: daily
dcr: daily
plan: Analytics
retention: 730
totalRetention: 2556

url: https://api.securitycenter.microsoft.com/api/configurationScore
scope: https://api.securitycenter.microsoft.com/.default
transform: single

columns:
  - name: ConfigurationScore
    type: real
